[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --prefix server",
  "npm install --prefix client --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "cd server && node server.js"

